//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSBWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParSy
    {
        public int PAR_ID { get; set; }
        public Nullable<int> INST_ID { get; set; }
        public int GRUPA_ID { get; set; }
        public int PARAMETR_ID { get; set; }
        public string PARAMETR_NAZWA { get; set; }
        public int PARAMETR_TYP { get; set; }
        public string WARTOSC { get; set; }
        public Nullable<int> WART_MIN { get; set; }
        public Nullable<int> WART_MAX { get; set; }
        public bool SHOW_IT { get; set; }
        public string INFO { get; set; }
    }
}
